[package]
name = "anyxml-uri"
version = "0.1.1"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "simple URI library for XML"
keywords = ["uri", "xml"]
rust-version.workspace = true

[dependencies]
