[package]
name = "anyxml-automata"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true
keywords.workspace = true
rust-version.workspace = true

[dependencies]
