name: cargo test --workspace
on:
  push:
    branches: 
      - master
      - develop

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build: [--release, --debug]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Fix git config to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Download xmlconf test
        run: deno run -A resources/get-xmlconf.ts
            
      - name: Check Rust version
        run: |
          rustup --version
          rustc --version
          cargo --version

      - name: Build crate with ${{ matrix.build }}
        run: cargo build ${{ matrix.build }}
            
      - name: Run `cargo test --workspace` with ${{ matrix.build }}
        run: cargo test --workspace ${{ matrix.build }}
